version = 2

[metadata]
name = "Lain and Gentoo Linux"
authors = [
    {"name" = "Goldy", "github" = "THEGOLDENPRO"}
]
tags = [
    "lain",
    "serial experiments",
    "serial experiments lain",
    "gentoo linux"
]