version = 2

[metadata]
name = "Takina Inoue and a ASUS mainboard"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
tags = [
    "lycoris recoil",
    "takina inoue",
    "asus",
    "mainboard",
    "motherboard"
]