[metadata]
name = "Takina Inoue and a ASUS mainboard"
author = {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
tags = [
    "lycoris recoil",
    "takina inoue",
    "asus",
    "mainboard",
    "motherboard"
]