version = 2

[metadata]
name = "Sanae Dekomori and Ubuntu"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
tags = [
    "chuunibyou demo koi ga shitai",
    "sanae dekomori",
    "ubuntu"
]