version = 2

[metadata]
name = "Satone inside Arch Linux"
authors = [
    {"name" = "Goldy", "github" = "THEGOLDENPRO"}
]
tags = [
    "Satone Shichimiya",
    "satone inside arch linux logo",
    "arch linux"
]
sources = [
    "https://www.reddit.com/r/chuunibyou/comments/hgjo35/ive_always_loved_shichimiya_8k_wallpaper/"
]