version = 2

[metadata]
name = "Koyume Koizuka and Rocky Linux"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
sources = [
    "https://cdn.ananas.moe/source/koyume_rocky.png"
]
tags = [
    "comic girls",
    "koyume koizuka",
    "rocky linux"
]
