version = 2

[metadata]
name = "Miyako Shikimori and Fedora"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
sources = [
    "https://otakuusamagazine.com/wp-content/uploads/2022/01/shikimori_KV2.jpg"
]
tags = [
    "Shikimori's Not Just a Cutie",
    "Miyako Shikimori",
    "fedora"
]
