version = 2

[metadata]
name = "Chisato Nishikigi and Linux Mint"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
tags = [
    "lycoris recoil",
    "chisato nishikigi",
    "linux mint"
]