version = 2

[metadata]
name = "Mashiro Shiina and Fedora"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
tags = [
    "the pet girl of sakurasou",
    "Mashiro Shiina",
    "fedora"
]