version = 2

[metadata]
name = "Misaki Takasaki and Alpine Linux"
authors = [
    {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
]
sources = [
    "https://www.manime.de/wp-content/uploads/2019/01/love_and_lies_vol_01_scr_07.jpg"
]
tags = [
    "Love and Lies",
    "Misaki Takasaki",
    "alpine linux"
]
