[metadata]
name = "Nanami Aoyama and Arch Linux but in gradient"
author = {"name" = "r3tr0ananas", "github" = "r3tr0ananas"}
tags = [
    "the pet girl of sakurasou",
    "Nanami Aoyama",
    "arch linux"
]