version = 2

[metadata]
name = "Ubuntu girl with text logo"
authors = [
    {"name" = "Goldy", "github" = "THEGOLDENPRO"}
]
sources = [
    "https://wallpapers.com/wallpapers/orange-anime-cat-girl-wearing-uniform-48yf2svg7s0bj4td.html"
]
tags = [
    "ubuntu",
    "linux",
    "text_logo"
]
