name: Parse images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download agc-parser
        run: wget -O agc-parser https://github.com/THEGOLDENPRO/anime-girls-and-computers/raw/agc-parser/agc-parser

      - name: Run agc-parser
        run: ./agc-parser
