name: Parse images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build agc-parser
        run: cargo build --release
      
      - name: Run agc-parser
        run: ./target/release/agc-parser